### PR TITLE
updated - last full-site scan label and date format

### PR DESCRIPTION
**Pull request by SteveJonesDev**
Fixes issue from pro repo: https://github.com/equalizedigital/accessibility-checker-pro/issues/121

### CODE REVIEW

**Comment by boonedev** [comment]
@SteveJonesDev What would you think about using the user-defined data/time format and adding an $include_time boolean in format_date? Something like this:

```public static function format_date( $date, $include_time = false ) {```
...
```
	if ( ! $include_time ) {
		$format = get_option( 'date_format' );
	} else {
		$format = get_option( 'date_format' ) . ' ' . get_option( 'time_format' );
	}
        if ( ! $format ) {
	     if ( $include_time ) {
		$format = 'j M Y g:i a';
	     } else {
		$format = 'j M Y';
	     }
     }
```

**Comment by SteveJonesDev** [comment]
@boonedev, the benefit to the user-defined time is different formats for different countries, right?

**Comment by boonedev** [comment]
That's right.

**Review by boonedev — APPROVED** [review]
Looks good.

**Comment by SteveJonesDev** [comment]
Also fixes: https://github.com/equalizedigital/accessibility-checker-pro/issues/120

**Pull request merged**
