### PR TITLE
Delete fix option keys on uninstall

### PR DESCRIPTION
**Pull request by pattonwebz**
This PR stores options keys so they can be later deleted if the plugin gets uninstalled

## Checklist

- [x] PR is linked to the main issue in the repo
- [ ] Tests are added that cover changes

### CODE REVIEW

**Comment by SteveJonesDev** [comment]
@pattonwebz is this ready for code review?

**Comment by pattonwebz** [comment]
@SteveJonesDev let me know what you think of the method used here. It feels janky but it does work. If you also think it's janky I will rethink it.

**Comment by SteveJonesDev** [comment]
At first look, it seems a bit odd. Is that update_option going to get called on every page load? We can't just return an array?

**Comment by pattonwebz** [comment]
Yeah, it gets called on all admin page loads. That's my main issue with it as well.

I didn't want to have to define an array of option keys manually because we are likely to forget to update them when we make changes. There's somewhere around 20+ options currently with the fixes so far.

**Comment by SteveJonesDev** [comment]
We could create a method in the class:

```php
<?php
public function get_option_field_slugs() {
    // Initialize an empty array for the slugs
    $slugs = [];

    // Apply the same filter to get the fields array, ensuring external modifications are included
    $fields = apply_filters('edac_filter_fixes_settings_fields', []);

    // Iterate through the fields to extract the slugs
    foreach ($fields as $field_id => $field) {
        // Add the field ID (slug) to the slugs array
        $slugs[] = $field_id;
    }

    // Return the array of slugs
    return $slugs;
}
```

and then output it in the uninstall file:

```php
<?php
// Step 1: Include the FixesPage class if necessary
require_once 'path/to/FixesPage.php'; // Adjust the path as necessary

// Step 2: Instantiate FixesPage
// Assuming 'manage_options' is a suitable capability for your use case
$fixesPage = new EqualizeDigital\AccessibilityChecker\Admin\AdminPage\FixesPage('manage_options');

// Step 3: Call the method
$optionFieldSlugs = $fixesPage->get_option_field_slugs();

// Use $optionFieldSlugs as needed
var_dump($optionFieldSlugs); // Just an example of usage
```

But I don't love this either.

I actually think we just manually add the options like we have for everything else. Keep it simple.

**Comment by pattonwebz** [comment]
Yeah I think I am leaning towards just the array of options method because we can't run code from the plugin inside the uninstall hook since it's already deactivated by that point

**Review by SteveJonesDev — APPROVED** [review]
LGTM

**Pull request merged**
